#!/bin/sh
########################################################################
# Begin $rc_base/init.d/guardian
#
# Description : Guardian Initscript
#
# Authors     : Kim Wölfel for ipfire.org
#
# Version     : 01.00
#
# Notes       :
#
########################################################################

. /etc/sysconfig/rc
. ${rc_functions}

eval $(/usr/local/bin/readhash /var/ipfire/guardian/settings)

function guardian_is_enabled() {
	[ "${GUARDIAN_ENABLED}" = "on" ]
}

case "$1" in
        start)
			guardian_is_enabled || exit 0

			boot_mesg "Starting Guardian..."
			loadproc /usr/local/bin/guardian.pl
	;;

	stop)
		if ([ ! -z $(pidofproc /usr/local/bin/guardian.pl) ]); then
			boot_mesg "Stopping Guardian..."
			killproc /usr/local/bin/guardian.pl
		fi
	;;

        status)
		statusproc /usr/local/bin/guardian.pl
	;;
                
	restart)
		$0 stop
		$0 start
	;;
 
	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
	;;
esac

# End $rc_base/init.d/guardian
